MGDSTRM-9748-Update FSO to Quarkus 2.13
bf2fc6cc711aee1a0c2a/kas-fleetshard pull request #862
Opened 2023-01-26 15:09 UTC by biswassri

2023-01-26 15:36 UTC, MikeEdgar requested changes

2023-01-26 15:36 UTC, MikeEdgar commented on pom.xml
>              </dependency>
I think this dependency can be removed entirely. We don't use it directly and it will be pulled in via Jackson.

2023-01-26 17:07 UTC, biswassri commented on pom.xml
>              </dependency>
Sure. I'll do that.

2023-01-26 17:59 UTC, MikeEdgar approved these changes
lgtm

2023-01-26 18:05 UTC, MikeEdgar commented
@shawkins , do we want to update to JOSDK 4.0.9 and fabric8 5.12.4 with this? There are code changes for the JOSDK update.

https://github.com/quarkiverse/quarkus-operator-sdk/releases/tag/4.0.7

2023-01-26 18:16 UTC, shawkins commented
> @shawkins , do we want to update to JOSDK 4.0.9 and fabric8 5.12.4 with this? There are code changes for the JOSDK update.

Yes. Generally they all need to move in lock step.

2023-01-26 18:21 UTC, biswassri commented
Sure! I'll update these dependencies also.

2023-01-26 18:34 UTC, rareddy commented
Do we not have an automatic dependency checker maven plugin for FSO?

2023-01-27 17:38 UTC, biswassri commented
> Do we not have an automatic dependency checker maven plugin for FSO?

Yes, but I don't think it's still configured completely yet. This was the PR https://github.com/bf2fc6cc711aee1a0c2a/kas-fleetshard/pull/848

2023-01-30 17:40 UTC, rareddy approved these changes
lgtm

2023-01-31 15:26 UTC, biswassri commented
@MikeEdgar @shawkins I will open another PR with the JOSDK and fabric8 upgrades and merge this one.

2023-01-31 15:30 UTC, merged